const fs = require('fs');
const pkg = require('../package.json');
const content = `// This file is auto-generated by scripts/update-version.js\nexport const version = \"${pkg.version}\";\n`;
fs.writeFileSync('src/version.ts', content); 